import type {NextPage} from 'next';
import Head from 'next/head';
import Title from '../components/Title';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>choose between options.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Title />
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
